import path from "node:path";
import type { ColumnDefinitions, MigrationBuilder } from "node-pg-migrate";
import { existsSync, readFileSync } from "node:fs";

export const shorthands: ColumnDefinitions | undefined = undefined;

export async function up(pgm: MigrationBuilder): Promise<void> {
  // 1. Define the SQL tables
  pgm.sql(`
    CREATE TABLE categories (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE
    );

    CREATE TABLE units_of_measure (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(50) NOT NULL UNIQUE
    );

    CREATE TABLE suppliers (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL UNIQUE,
      country VARCHAR(5) NOT NULL,
      website VARCHAR(255)
    );

    CREATE TABLE products (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_name VARCHAR(255) NOT NULL,
      category_id INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
      supplier_id INT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
      unit_price NUMERIC(10, 2) NOT NULL,
      currency VARCHAR(3) NOT NULL,
      unit_of_measure_id INT NOT NULL REFERENCES units_of_measure(id) ON DELETE RESTRICT,
      lead_time_days INT NOT NULL
    );
  `);

  // 2. Read the JSON file using Node.js
  const jsonFilePath = path.join(__dirname, "../seed.json");

  // If the file doesn't exist during a purely structural migration, skip the data seed
  if (!existsSync(jsonFilePath)) {
    console.warn("seed.json not found, skipping data seeding.");
    return;
  }

  const fileData = readFileSync(jsonFilePath, "utf-8");

  // 3. Define the CTE and QUEUE it using pgm.sql with named parameters
  pgm.sql(
    `
      WITH raw_data AS (
        SELECT $json$${fileData}$json$::jsonb AS doc
      ),
      -- Expand the main JSON array into individual supplier objects
      supplier_elems AS (
        SELECT jsonb_array_elements(doc) AS supplier_node FROM raw_data
      ),
      -- Extract supplier details and expand their products array
      extracted_data AS (
        SELECT 
          supplier_node->>'name' AS supplier_name,
          supplier_node->>'country' AS country,
          supplier_node->>'website' AS website,
          jsonb_array_elements(supplier_node->'products') AS product_node
        FROM supplier_elems
      ),
      -- 1. Insert unique Suppliers
      -- DO UPDATE ensures we always get an ID returned, even if it already existed
      inserted_suppliers AS (
        INSERT INTO suppliers (name, country, website)
        SELECT DISTINCT supplier_name, country, website FROM extracted_data
        ON CONFLICT (name) DO UPDATE SET country = EXCLUDED.country
        RETURNING id, name
      ),
      -- 2. Insert unique Categories
      inserted_categories AS (
        INSERT INTO categories (name)
        SELECT DISTINCT product_node->>'category' FROM extracted_data
        ON CONFLICT (name) DO NOTHING
        RETURNING id, name
      ),
      -- Fetch categories (Combine newly inserted + existing to solve CTE visibility rule)
      all_categories AS (
        SELECT id, name FROM inserted_categories
        UNION ALL
        SELECT id, name FROM categories
      ),
      -- 3. Insert unique Units of Measurement (UOM)
      inserted_uoms AS (
        INSERT INTO units_of_measure (name)
        SELECT DISTINCT product_node->>'unit_of_measure' FROM extracted_data
        ON CONFLICT (name) DO NOTHING
        RETURNING id, name
      ),
      -- Fetch UOMs (Combine newly inserted + existing)
      all_uoms AS (
        SELECT id, name FROM inserted_uoms
        UNION ALL
        SELECT id, name FROM units_of_measure
      )
      -- 4. Insert Products using the resolved foreign keys from the CTEs above
      INSERT INTO products (
        product_name, 
        category_id, 
        supplier_id, 
        unit_price, 
        currency, 
        unit_of_measure_id, 
        lead_time_days
      )
      SELECT 
        ed.product_node->>'product_name',
        c.id,
        s.id,
        (ed.product_node->>'unit_price')::NUMERIC,
        ed.product_node->>'currency',
        u.id,
        (ed.product_node->>'lead_time_days')::INT
      FROM extracted_data ed
      JOIN inserted_suppliers s ON s.name = ed.supplier_name
      JOIN all_categories c ON c.name = (ed.product_node->>'category')
      JOIN all_uoms u ON u.name = (ed.product_node->>'unit_of_measure');
    `,
  );
}

export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`
    DROP TABLE IF EXISTS products;
    DROP TABLE IF EXISTS suppliers;
    DROP TABLE IF EXISTS units_of_measure;
    DROP TABLE IF EXISTS categories;
  `);
}
