/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SuppliersNewRouteImport } from './routes/suppliers.new'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers.$supplierId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as SuppliersSupplierIdIndexRouteImport } from './routes/suppliers.$supplierId.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as SuppliersSupplierIdNewProductRouteImport } from './routes/suppliers.$supplierId.new-product'
import { Route as ProjectsProjectIdNewSpecItemRouteImport } from './routes/projects.$projectId.new-spec-item'
import { Route as ProjectsProjectIdSpecItemsSpecItemIdRouteImport } from './routes/projects.$projectId.spec-items.$specItemId'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliersRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const SuppliersNewRoute = SuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/$supplierId',
  path: '/$supplierId',
  getParentRoute: () => SuppliersRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const SuppliersSupplierIdIndexRoute =
  SuppliersSupplierIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SuppliersSupplierIdRoute,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const SuppliersSupplierIdNewProductRoute =
  SuppliersSupplierIdNewProductRouteImport.update({
    id: '/new-product',
    path: '/new-product',
    getParentRoute: () => SuppliersSupplierIdRoute,
  } as any)
const ProjectsProjectIdNewSpecItemRoute =
  ProjectsProjectIdNewSpecItemRouteImport.update({
    id: '/new-spec-item',
    path: '/new-spec-item',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSpecItemsSpecItemIdRoute =
  ProjectsProjectIdSpecItemsSpecItemIdRouteImport.update({
    id: '/spec-items/$specItemId',
    path: '/spec-items/$specItemId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/projects/$projectId/new-spec-item': typeof ProjectsProjectIdNewSpecItemRoute
  '/suppliers/$supplierId/new-product': typeof SuppliersSupplierIdNewProductRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/suppliers/$supplierId/': typeof SuppliersSupplierIdIndexRoute
  '/projects/$projectId/spec-items/$specItemId': typeof ProjectsProjectIdSpecItemsSpecItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects/new': typeof ProjectsNewRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/projects/$projectId/new-spec-item': typeof ProjectsProjectIdNewSpecItemRoute
  '/suppliers/$supplierId/new-product': typeof SuppliersSupplierIdNewProductRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdIndexRoute
  '/projects/$projectId/spec-items/$specItemId': typeof ProjectsProjectIdSpecItemsSpecItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/projects/$projectId/new-spec-item': typeof ProjectsProjectIdNewSpecItemRoute
  '/suppliers/$supplierId/new-product': typeof SuppliersSupplierIdNewProductRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/suppliers/$supplierId/': typeof SuppliersSupplierIdIndexRoute
  '/projects/$projectId/spec-items/$specItemId': typeof ProjectsProjectIdSpecItemsSpecItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects'
    | '/signup'
    | '/suppliers'
    | '/projects/$projectId'
    | '/projects/new'
    | '/suppliers/$supplierId'
    | '/suppliers/new'
    | '/projects/'
    | '/suppliers/'
    | '/projects/$projectId/new-spec-item'
    | '/suppliers/$supplierId/new-product'
    | '/projects/$projectId/'
    | '/suppliers/$supplierId/'
    | '/projects/$projectId/spec-items/$specItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/new'
    | '/suppliers/new'
    | '/projects'
    | '/suppliers'
    | '/projects/$projectId/new-spec-item'
    | '/suppliers/$supplierId/new-product'
    | '/projects/$projectId'
    | '/suppliers/$supplierId'
    | '/projects/$projectId/spec-items/$specItemId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects'
    | '/signup'
    | '/suppliers'
    | '/projects/$projectId'
    | '/projects/new'
    | '/suppliers/$supplierId'
    | '/suppliers/new'
    | '/projects/'
    | '/suppliers/'
    | '/projects/$projectId/new-spec-item'
    | '/suppliers/$supplierId/new-product'
    | '/projects/$projectId/'
    | '/suppliers/$supplierId/'
    | '/projects/$projectId/spec-items/$specItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SignupRoute: typeof SignupRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/suppliers/new': {
      id: '/suppliers/new'
      path: '/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof SuppliersNewRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/suppliers/$supplierId/': {
      id: '/suppliers/$supplierId/'
      path: '/'
      fullPath: '/suppliers/$supplierId/'
      preLoaderRoute: typeof SuppliersSupplierIdIndexRouteImport
      parentRoute: typeof SuppliersSupplierIdRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/suppliers/$supplierId/new-product': {
      id: '/suppliers/$supplierId/new-product'
      path: '/new-product'
      fullPath: '/suppliers/$supplierId/new-product'
      preLoaderRoute: typeof SuppliersSupplierIdNewProductRouteImport
      parentRoute: typeof SuppliersSupplierIdRoute
    }
    '/projects/$projectId/new-spec-item': {
      id: '/projects/$projectId/new-spec-item'
      path: '/new-spec-item'
      fullPath: '/projects/$projectId/new-spec-item'
      preLoaderRoute: typeof ProjectsProjectIdNewSpecItemRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/spec-items/$specItemId': {
      id: '/projects/$projectId/spec-items/$specItemId'
      path: '/spec-items/$specItemId'
      fullPath: '/projects/$projectId/spec-items/$specItemId'
      preLoaderRoute: typeof ProjectsProjectIdSpecItemsSpecItemIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdNewSpecItemRoute: typeof ProjectsProjectIdNewSpecItemRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdSpecItemsSpecItemIdRoute: typeof ProjectsProjectIdSpecItemsSpecItemIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdNewSpecItemRoute: ProjectsProjectIdNewSpecItemRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdSpecItemsSpecItemIdRoute:
    ProjectsProjectIdSpecItemsSpecItemIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SuppliersSupplierIdRouteChildren {
  SuppliersSupplierIdNewProductRoute: typeof SuppliersSupplierIdNewProductRoute
  SuppliersSupplierIdIndexRoute: typeof SuppliersSupplierIdIndexRoute
}

const SuppliersSupplierIdRouteChildren: SuppliersSupplierIdRouteChildren = {
  SuppliersSupplierIdNewProductRoute: SuppliersSupplierIdNewProductRoute,
  SuppliersSupplierIdIndexRoute: SuppliersSupplierIdIndexRoute,
}

const SuppliersSupplierIdRouteWithChildren =
  SuppliersSupplierIdRoute._addFileChildren(SuppliersSupplierIdRouteChildren)

interface SuppliersRouteChildren {
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRouteWithChildren
  SuppliersNewRoute: typeof SuppliersNewRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersSupplierIdRoute: SuppliersSupplierIdRouteWithChildren,
  SuppliersNewRoute: SuppliersNewRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SignupRoute: SignupRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
